routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('products', App\Http\Controllers\ProductController::class);
    Route::resource('shoppingCart', App\Http\Controllers\ShoppingCartController::class);

    Route::get('/showCheckout', 'App\Http\Controllers\ShoppingCartController@showCheckout');

});

Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table="products";

    protected $fillable=[
        'titulo',
        'descripcion',
        'precio',
        'porcentajeDescuento',
        'raiting',
        'stock',
        'marca',
        'miniatura'
    ];
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table="roles";

    protected $fillable=['name', 'description'];
}

app/Models/ShoppingCart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ShoppingCart extends Model
{
    use HasFactory;
    protected $table="shopping_cart";

    protected $fillable=[
        'cantidadProducto',
        'user_id',
        'product_id'
    ];

    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function product(){
        return $this->belongsTo(Product::class,'product_id','id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role(){
        return $this->belongsTo(Role::class,'role_id','id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $products=Product::all();
        return view('home', compact('products'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=Product::all();
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Product::create($request->all());
        return redirect()->route('products.index')->with('success', '¡Producto registrado exitosamente!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update($request->all());
        return redirect()->route('products.index')->with('success', '¡Producto actualizado exitosamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

app/Http/Controllers/ShoppingCartController.php
<?php

namespace App\Http\Controllers;

use App\Models\ShoppingCart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ShoppingCartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shoppingCarts=ShoppingCart::where('user_id', '=', Auth::user()->id)->get();
        $totalAPagar=0;

        foreach($shoppingCarts as $shoppingCart){
            $totalAPagar+=$shoppingCart->product->precio;
        }

        return view('shoppingCart.index', compact('shoppingCarts', 'totalAPagar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            ShoppingCart::create([
                'cantidadProducto' => 1,
                'user_id' => $request->user_id,
                'product_id' => $request->product_id,
            ]);
        }catch(Exception $e){
            dd($e);
        }

        return redirect()->route('home')->with('success', '¡Producto agregado al carrito exitosamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ShoppingCart  $shoppingCart
     * @return \Illuminate\Http\Response
     */
    public function destroy(ShoppingCart $shoppingCart)
    {
        $shoppingCart->delete();
        return redirect()->route('shoppingCart.index')->with('success', '¡Producto removido exitosamente!');
    }

    public function showCheckout(){
        $shoppingCarts=ShoppingCart::where('user_id', '=', Auth::user()->id)->get();
        $totalAPagar=0;

        foreach($shoppingCarts as $shoppingCart){
            $totalAPagar+=$shoppingCart->product->precio;
        }

        return view('shoppingCart.showCheckout', compact('totalAPagar'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Lo destacado de hoy:') }}</div>
                <div class="card-body">
                    <div class="row">
                        @foreach ($products as $product)
                            <div class="col-md-4" style="padding-bottom: 3%;">
                                <div class="card">
                                    <div class="card-header"><a href="{{ route('products.show', $product->id) }}"><h5 style="text-align: center;">{{ $product->titulo }}</h5></a></div>

                                    <div class="card-body" style="text-align: center;"><img style="max-height: 200px; max-width: 350px;" src="{{ $product->miniatura }}" alt="{{ $product->miniatura }}"></div>

                                    <div class="card-footer" style="text-align: left;">
                                        <i class="fa-solid fa-star"></i> {{ $product->raiting ?? '?' }} de 5 <br>
                                        <i class="fa-solid fa-sack-dollar"></i> <i class="fa-solid fa-dollar-sign"></i> {{ $product->precio }} <br>
                                        <span style="font-weight: bold;"><i class="fa-solid fa-tags"></i> Descuento del: {{ $product->porcentajeDescuento}} <i class="fa-solid fa-percent"></i></span><br>

                                        <div style="text-align: center; padding-top: 3%;">
                                            @if (Auth::user()->role->name!="Cliente")
                                                <a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary"><i class="fa-solid fa-pencil"></i> Editar producto</a><br>
                                            @else
                                                @if ($product->stock<=0)
                                                    <div class="btn btn-danger"><i class="fa-solid fa-cart-arrow-down"></i> No quedan unidades disponibles</div><br>
                                                @else
                                                    <form action="{{ route('shoppingCart.store') }}" method="POST" enctype="multipart/form-data">
                                                        @csrf
                                                        <input type="hidden" value="{{ $product->id }}" name="product_id" id="product_id">
                                                        <input type="hidden" value="{{ Auth::user()->id }}" name="user_id" id="user_id">
                                                        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-cart-plus"></i> ¡Comprar ahora!</button><br>
                                                    </form>
                                                @endif
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Resolución de caso 4 - Javier Vintimilla</title>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">
    <script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script>

</head>
<body class="d-flex flex-column min-vh-100">
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    VentaVirtual
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        @auth
                            @if (Auth::user()->role->name!="Cliente")
                                <div class="nav-item">
                                    <a href="{{ route('products.index') }}" class="nav-link"><i class="fa-solid fa-boxes-packing"></i> Mis productos</a>
                                </div>
                            @else
                            <div class="nav-item">
                                <a href="{{ route('shoppingCart.index') }}" class="nav-link"><i class="fa-solid fa-cart-shopping"></i> Mis compras</a>
                            </div>
                            @endif
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar sesión') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrarse') }}</a>
                                </li>
                            @endif
                        @else

                        @auth
                            <div class="container-fluid">
                                <form class="d-flex">
                                    <input class="form-control me-2" type="search" placeholder="Buscar un producto..." aria-label="Search">
                                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                                </form>
                            </div>
                        @endauth

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <i class="fa-solid fa-user"></i> {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    <i class="fa-solid fa-right-from-bracket"></i> {{ __('Cerrar sesión') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <footer class="bg-body-tertiary text-center text-lg-start mt-auto">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: #212529; color: #fafafa;">
            Realizado por:
            <a href="https://gitlab.com/XavierEduardo99">Javier Vintimilla (100-RED)</a>
            | 2024.
        </div>
        <!-- Copyright -->
    </footer>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4><i class="fa-solid fa-cash-register"></i> Registro de producto para la venta</h4>
                </div>

                <div class="card-body">
                    <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="titulo">Titulo de la publicación:</label>
                                    <input type="text" class="form-control" id="titulo" name="titulo" maxlength="128" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="precio">Precio del producto:</label>
                                    <input type="number" class="form-control" id="precio" name="precio" min="1" max="999999" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="porcentajeDescuento">Porcentaje de descuento para el producto:</label>
                                    <input type="number" class="form-control" id="" name="porcentajeDescuento" min="0" max="100" maxlength="porcentajeDescuento" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="stock">Stock del producto:</label>
                                    <input type="number" class="form-control" id="stock" name="stock" min="1" max="999" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="marca">Marca del producto:</label>
                                    <input type="text" class="form-control" id="marca" name="marca" maxlength="128" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="miniatura">Enlace de imagen del producto:</label>
                                    <input type="text" class="form-control" id="miniatura" name="miniatura">
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="descripcion">Descripción del producto:</label>
                                    <textarea name="descripcion" id="descripcion" cols="30" rows="5" class="form-control" required></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row" style="padding-top: 2%;">
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar producto nuevo</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4><i class="fa-solid fa-cash-register"></i> Editar producto para la venta</h4>
                </div>

                <div class="card-body">
                    <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="titulo">Titulo de la publicación:</label>
                                    <input type="text" class="form-control" id="titulo" name="titulo" maxlength="128" value="{{ $product->titulo }}" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="precio">Precio del producto:</label>
                                    <input type="number" class="form-control" id="precio" name="precio" min="1" max="999999" value="{{ $product->precio }}" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="porcentajeDescuento">Porcentaje de descuento para el producto:</label>
                                    <input type="number" class="form-control" id="" name="porcentajeDescuento" min="0" max="100" step="any" maxlength="porcentajeDescuento" value="{{ $product->porcentajeDescuento }}" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="stock">Stock del producto:</label>
                                    <input type="number" class="form-control" id="stock" name="stock" min="1" max="999" value="{{ $product->stock }}" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="marca">Marca del producto:</label>
                                    <input type="text" class="form-control" id="marca" name="marca" maxlength="128" value="{{ $product->marca }}" required>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="miniatura">Enlace de imagen del producto:</label>
                                    <input type="text" class="form-control" id="miniatura" name="miniatura" value="{{ $product->miniatura }}">
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="descripcion">Descripción del producto:</label>
                                    <textarea name="descripcion" id="descripcion" cols="30" rows="5" class="form-control" required>{{ $product->descripcion }}</textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row" style="padding-top: 2%;">
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Guardar producto actualiado</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>{{ $product->marca }} - {{ $product->titulo }}</h3>
                        <h5><i class="fa-solid fa-star"></i> {{ $product->raiting ?? '?' }} de 5</h5>
                        <h5><i class="fa-solid fa-sack-dollar"></i> <i class="fa-solid fa-dollar-sign"></i> {{ $product->precio }} <span style="font-weight: bold;"> - Tiene un descuento del {{ $product->porcentajeDescuento }} <i class="fa-solid fa-percent"></i></span></h5>
                        @if ($product->stock > 0)
                            <form action="{{ route('shoppingCart.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <input type="hidden" id="user_id" name="user_id" value="{{ Auth::user()->id }}">
                                <input type="hidden" id="product_id" name="product_id" value="{{ $product->id }}">
                                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-cart-shopping"></i> ¡Comprar ahora!</button><br>
                            </form>
                        @else
                            <span><span><i class="fa-solid fa-triangle-exclamation"></i>  No quedan más unidades disponibles...</span>
                        @endif
                    </div>

                    <div class="card-body">
                        <div style="text-align: center;"><img style="max-width: 600px;" src="{{ $product->miniatura }}" alt="{{ $product->miniatura }}"></div>
                        <div style="padding-top: 2%;">
                            <span style="font-weight: bold;">Descripción del producto:</span>
                            <textarea class="form-control" cols="30" rows="5" readonly>{{ $product->descripcion }}</textarea>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div style="text-align: center;">
                            Quedan: {{ $product->stock }} unidades disponibles
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/shoppingCart/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h4><i class="fa-solid fa-cart-shopping"></i> Su carrito de compras</h4></div>

                <div class="card-body">
                    <table class="table table-striped table-hover" id="mainTable">
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Costo</th>
                                <th>Cantidad</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($shoppingCarts as $shoppingCart)
                                <tr>
                                    <td>{{ $shoppingCart->product->titulo }}</td>
                                    <td>${{ $shoppingCart->product->precio }}</td>
                                    <td>{{ $shoppingCart->cantidadProducto }}</td>

                                    <td>
                                        <form method="POST" action="{{ route('shoppingCart.destroy', $shoppingCart->id) }}">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button type="submit" class="btn btn-sm btn-danger warning show_confirm"><i class="fa-solid fa-xmark"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>

                        <tfoot>
                            <tr>
                                <th>Producto</th>
                                <th>Costo</th>
                                <th>Cantidad</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>

                <div class="card-footer" style="text-align: right;">
                    <h5>Total a cancelar: ${{ $totalAPagar }}</h5>
                </div>

                <div style="text-align: center;">
                    @if (sizeof($shoppingCarts)>0)
                        <a class="btn btn-primary" href="{{ url('/showCheckout') }}"><i class="fa-solid fa-credit-card"></i> Proceder a pagar</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        new DataTable('#mainTable');
    });
</script>

@endsection